### ISSUE TITLE
18 days ago ,don't  stop work

### ISSUE THREAD

**Issue by thinker-gao** [swow/swow#80]
18 days ago ,don't  stop work

**Comment by limingxinleo** [comment]
你看ci分支，现在ci分支才是开发分支。

**Comment by twose** [comment]
I am working on [libcat](https://github.com/libcat/libcat), which is a dependency of Swow.
And Swow team is working on other important parts of the PHP/Swow/Swoole ecosystem. (now some of us are developing for PHP docker image with debug symbol)
We never stop.

**Comment by dixyes** [comment]
Busying on [swow-bcreports](https://github.com/dixyes/swow-bcreports) (automatic behavior change reports generation) and other things...

Behavior change reports indicates behavior changes caused by swow, solving `stream_set_blocking()` problems which found by bcreports needs libcat works, that's a heavy task.

Latest development codes may be pushed to ci branch to run full ci tests, then sync to trunk to prove stablity.
